//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bosch_ImportData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp1\\VaultWorkFolderBosch\\")]
        public string tempVaultRootPath {
            get {
                return ((string)(this["tempVaultRootPath"]));
            }
            set {
                this["tempVaultRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sites\\CtP_TEF\\project\\")]
        public string ProjectRootPath {
            get {
                return ((string)(this["ProjectRootPath"]));
            }
            set {
                this["ProjectRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATMOLIB\\")]
        public string AtmoRootPath {
            get {
                return ((string)(this["AtmoRootPath"]));
            }
            set {
                this["AtmoRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContentCenter\\")]
        public string ContentCenterRootPath {
            get {
                return ((string)(this["ContentCenterRootPath"]));
            }
            set {
                this["ContentCenterRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATMOLIB\\Library\\Catalog\\")]
        public string Catalog {
            get {
                return ((string)(this["Catalog"]));
            }
            set {
                this["Catalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATMOLIB\\Produtos Bosch\\")]
        public string ProdutosBosch {
            get {
                return ((string)(this["ProdutosBosch"]));
            }
            set {
                this["ProdutosBosch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContentCenter\\en-US\\")]
        public string EnglishCC {
            get {
                return ((string)(this["EnglishCC"]));
            }
            set {
                this["EnglishCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContentCenter\\pt-BR\\")]
        public string PortugueseCC {
            get {
                return ((string)(this["PortugueseCC"]));
            }
            set {
                this["PortugueseCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VaultDB {
            get {
                return ((string)(this["VaultDB"]));
            }
            set {
                this["VaultDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VaultSRV {
            get {
                return ((string)(this["VaultSRV"]));
            }
            set {
                this["VaultSRV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VaultUser {
            get {
                return ((string)(this["VaultUser"]));
            }
            set {
                this["VaultUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VaultPassword {
            get {
                return ((string)(this["VaultPassword"]));
            }
            set {
                this["VaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\KeepCAD\\ImportacaoArquivos\\StandardIPJ.ipj")]
        public string DefaultIPJ {
            get {
                return ((string)(this["DefaultIPJ"]));
            }
            set {
                this["DefaultIPJ"] = value;
            }
        }
    }
}
